//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projAttend_DLL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyIzMCI6IjMwIiwiMTMwIjoiMTMwIiwiMTI5IjoiMTI5" +
            "IiwiMTI4IjoiMTI4IiwiMTI3IjoiMTI3IiwiMTI2IjoiMTI2IiwiMTI1IjoiMTI1IiwiMzkiOiIzOSIs" +
            "IjM4IjoiMzgiLCIzNyI6IjM3IiwiMzYiOiIzNiIsIjM1IjoiMzUiLCIzNCI6IjM0IiwiMzMiOiIzMyIs" +
            "IjMyIjoiMzIiLCIzMSI6IjMxIiwiMTMxIjoiMTMxIiwiMTMyIjoiMTMyIiwiNzAiOiI3MCIsIjcxIjoi" +
            "NzEiLCI4NSI6Ijg1IiwiOTUiOiI5NSIsIjk2IjoiOTYiLCI5NyI6Ijk3IiwiOTgiOiI5OCIsIjk5Ijoi" +
            "OTkiLCIxMDAiOiIxMDAiLCIxMDEiOiIxMDEiLCIxMDIiOiIxMDIiLCI0NiI6IjQ2IiwiNDkiOiI0OSIs" +
            "IjQ3IjoiNDciLCI1MCI6IjUwIiwiNDgiOiI0OCIsIjUxIjoiNTEiLCIxMDUiOiIxMDUiLCIxMDQiOiIx" +
            "MDQiLCIxMDMiOiIxMDMiLCI5NCI6Ijk0IiwiOTMiOiI5MyIsIjkyIjoiOTIiLCI5MSI6IjkxIiwiOTAi" +
            "OiI5MCIsIjg5IjoiODkiLCI4NCI6Ijg0IiwiODciOiI4NyIsIjg2IjoiODYiLCIxMDYiOiIxMDYiLCI4" +
            "MyI6IjgzIiwiODIiOiI4MiIsIjgxIjoiODEiLCI4MCI6IjgwIiwiNzkiOiI3OSIsIjc4IjoiNzgiLCI4" +
            "OCI6Ijg4IiwiMTA3IjoiMTA3IiwiMTM0IjoiMTM0IiwiMTA5IjoiMTA5IiwiMTM4IjoiMTM4IiwiMTM3" +
            "IjoiMTM3IiwiMTM2IjoiMTM2IiwiMTM1IjoiMTM1IiwiNzciOiI3NyIsIjEzMyI6IjEzMyIsIjEyNCI6" +
            "IjEyNCIsIjEyMyI6IjEyMyIsIjEyMiI6IjEyMiIsIjEwOCI6IjEwOCIsIjEyMCI6IjEyMCIsIjExOCI6" +
            "IjExOCIsIjExNyI6IjExNyIsIjExNiI6IjExNiIsIjExNSI6IjExNSIsIjExNCI6IjExNCIsIjExMyI6" +
            "IjExMyIsIjExMiI6IjExMiIsIjExMSI6IjExMSIsIjExMCI6IjExMCIsIjExOSI6IjExOSIsIjc2Ijoi" +
            "NzYiLCI1NyI6IjU3IiwiNzQiOiI3NCIsIjQxIjoiNDEiLCI0MCI6IjQwIiwiMjkiOiIyOSIsIjI4Ijoi" +
            "MjgiLCIyNyI6IjI3IiwiMjYiOiIyNiIsIjI1IjoiMjUiLCIyNCI6IjI0IiwiMjMiOiIyMyIsIjIyIjoi" +
            "MjIiLCIyMSI6IjIxIiwiMjAiOiIyMCIsIjE5IjoiMTkiLCIxOCI6IjE4IiwiMTciOiIxNyIsIjE2Ijoi" +
            "MTYiLCIxNSI6IjE1IiwiMTQiOiIxNCIsIjEzIjoiMTMiLCI0MiI6IjQyIiwiNDMiOiI0MyIsIjQ0Ijoi" +
            "NDQiLCI0NSI6IjQ1IiwiNzMiOiI3MyIsIjcyIjoiNzIiLCI2OSI6IjY5IiwiNjgiOiI2OCIsIjY3Ijoi" +
            "NjciLCI2NiI6IjY2IiwiNjUiOiI2NSIsIjY0IjoiNjQiLCI2MyI6IjYzIiwiNzUiOiI3NSIsIjYyIjoi" +
            "NjIiLCI2MCI6IjYwIiwiNTkiOiI1OSIsIjU4IjoiNTgiLCIxMzkiOiIxMzkiLCI1NiI6IjU2IiwiNTUi" +
            "OiI1NSIsIjU0IjoiNTQiLCI1MyI6IjUzIiwiNTIiOiI1MiIsIjYxIjoiNjEiLCIxNDAiOiIxNDAiLCIx" +
            "IjoiMSIsIjIiOiIyIiwiNiI6IjYiLCI3IjoiNyIsIjgiOiI4IiwiOSI6IjkiLCJleHAiOjE1NzA3OTA1" +
            "NzQsImlzcyI6ImJhYmFyYW0uY29tIiwiYXVkIjoiYmFiYXJhbS5jb20ifQ.MwszAHmad0XedDKitI8O0" +
            "4x3AON1iN3QeqYNgPV58LI")]
        public string tokken {
            get {
                return ((string)(this["tokken"]));
            }
            set {
                this["tokken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("machineadmin")]
        public string user_name {
            get {
                return ((string)(this["user_name"]));
            }
            set {
                this["user_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jnZWe3S+++aQtpmKlibdOA==")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string company_id {
            get {
                return ((string)(this["company_id"]));
            }
            set {
                this["company_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string emp_id {
            get {
                return ((string)(this["emp_id"]));
            }
            set {
                this["emp_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int fromday {
            get {
                return ((int)(this["fromday"]));
            }
            set {
                this["fromday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int today {
            get {
                return ((int)(this["today"]));
            }
            set {
                this["today"] = value;
            }
        }
    }
}
